//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProducts
    {
        public string projectCode { get; set; }
        public string productSerialNumber { get; set; }
        public string productBrand { get; set; }
        public string productModel { get; set; }
        public System.DateTime registerDateTime { get; set; }
        public int productAmount { get; set; }
        public System.DateTime productWarrantyStartDate { get; set; }
        public string productServiceContact { get; set; }
        public string productFeatures { get; set; }
        public string productImage { get; set; }
        public System.DateTime productWarrantyFinishDate { get; set; }
        public string productProvider { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
