//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int requestID { get; set; }
        public string requestUsername { get; set; }
        public string requestSubjectTitle { get; set; }
        public string requestCategoryName { get; set; }
        public System.DateTime requestDateTime { get; set; }
        public string requestMessage { get; set; }
        public string requestReceiverID { get; set; }
        public bool requestStatus { get; set; }
    }
}
